# Generated by Django 5.1.6 on 2025-02-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_productos_idproducto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteRocha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'clienteslf',
            },
        ),
        migrations.CreateModel(
            name='PedidoJD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=80)),
                ('producto', models.CharField(max_length=120)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'pedidosjd',
            },
        ),
        migrations.CreateModel(
            name='PerfilJorge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_perfil', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'perfiljp',
            },
        ),
        migrations.CreateModel(
            name='UsuariosJD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'usuariosjd',
            },
        ),
        migrations.CreateModel(
            name='UsuariosJorge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=150)),
                ('email_usuario', models.EmailField(max_length=254, unique=True)),
                ('contrasena_usuario', models.CharField(max_length=255)),
                ('perfil', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'usuariosjp',
            },
        ),
        migrations.AlterModelTable(
            name='productos',
            table='productos',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
